//--------------------------------------------------------------------------------
// Auto-generated by LiteX (f813e9c12) on 2026-05-05 16:40:05
//--------------------------------------------------------------------------------
#ifndef __GENERATED_MEM_H
#define __GENERATED_MEM_H

#ifndef ROM_BASE
#define ROM_BASE 0x00000000L
#define ROM_SIZE 0x00010000
#endif

#ifndef SRAM_BASE
#define SRAM_BASE 0x10000000L
#define SRAM_SIZE 0x00004000
#endif

#ifndef CSR_BASE
#define CSR_BASE 0xf0000000L
#define CSR_SIZE 0x00020000
#endif

#ifndef MEM_REGIONS
#define MEM_REGIONS "ROM   0x00000000 0x10000 \nSRAM  0x10000000 0x4000 \nCSR   0xf0000000 0x20000 "
#endif
#endif
