//--------------------------------------------------------------------------------
// Auto-generated by LiteX (f813e9c12) on 2026-05-04 15:46:38
//--------------------------------------------------------------------------------
#ifndef __GENERATED_MEM_H
#define __GENERATED_MEM_H

#ifndef CSR_BASE
#define CSR_BASE 0x00000000L
#define CSR_SIZE 0x00020000
#endif

#ifndef MEM_REGIONS
#define MEM_REGIONS "CSR  0x00000000 0x20000 "
#endif
#endif
